// auth
export const AUTH = "AUTH";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

// 로그인
export const LOGIN = "LOGIN";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// 로그아웃
export const LOGOUT = "LOGOUT";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// 메뉴 열기
export const MENU_OPEN = "MENU_OPEN";
export const MENU_OPEN_REQUEST = "MENU_OPEN_REQUEST";
// 메뉴 닫기
export const MENU_CLOSE = "MENU_CLOSE";
export const MENU_CLOSE_REQUEST = "MENU_CLOSE_REQUEST";

// home 페이지 데이터 요청
export const HOME_DATA = "HOME_DATA";
export const HOME_DATA_REQUEST = "HOME_DATA_REQUEST";
export const HOME_DATA_SUCCESS = "HOME_DATA_SUCCESS";
export const HOME_DATA_FAILURE = "HOME_DATA_FAILURE";

// trend 페이지 데이터 요청
export const TREND_DATA = "TREND_DATA";
export const TREND_DATA_REQUEST = "TREND_DATA_REQUEST";
export const TREND_DATA_SUCCESS = "TREND_DATA_SUCCESS";
export const TREND_DATA_FAILURE = "TREND_DATA_FAILURE";

// report 페이지 데이터 요청
export const REPORT_DATA = "REPORT_DATA";
export const REPORT_DATA_REQUEST = "REPORT_DATA_REQUEST";
export const REPORT_DATA_SUCCESS = "REPORT_DATA_SUCCESS";
export const REPORT_DATA_FAILURE = "REPORT_DATA_FAILURE";

// diary 페이지 데이터 요청
export const DIARY_DATA = "DIARY_DATA";
export const DIARY_DATA_REQUEST = "DIARY_DATA_REQUEST";
export const DIARY_DATA_SUCCESS = "DIARY_DATA_SUCCESS";
export const DIARY_DATA_FAILURE = "DIARY_DATA_FAILURE";

// 장소 변경에 대한 데이터 변경 요청
export const SAVE_SITEID = "SAVE_SITEID";
export const SAVE_SITEID_REQUEST = "SAVE_SITEID_REQUEST";
export const SAVE_SITEID_SUCCESS = "SAVE_SITEID_SUCCESS";
export const SAVE_SITEID_FAILURE = "SAVE_SITEID_FAILURE";

// 일지 정보 등록 요청
export const SAVE_DIARYINFO = "SAVE_DIARYINFO";
export const SAVE_DIARYINFO_REQUEST = "SAVE_DIARYINFO_REQUEST";
export const SAVE_DIARYINFO_SUCCESS = "SAVE_DIARYINFO_SUCCESS";
export const SAVE_DIARYINFO_FAILURE = "SAVE_DIARYINFO_FAILURE";

// 일지 리스트 state 저장
export const SAVE_DIARYLIST = "SAVE_DIARYLIST";
export const SAVE_DIARYLIST_REQUEST = "SAVE_DIARYLIST_REQUEST";
export const SAVE_DIARYLIST_SUCCESS = "SAVE_DIARYLIST_SUCCESS";
export const SAVE_DIARYLIST_FAILURE = "SAVE_DIARYLIST_FAILURE";
