// auth
export const AUTH = "AUTH";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

// 로그인
export const LOGIN = "LOGIN";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// 로그아웃
export const LOGOUT = "LOGOUT";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// 메뉴 열기
export const MENU_OPEN = "MENU_OPEN";
export const MENU_OPEN_REQUEST = "MENU_OPEN_REQUEST";
// 메뉴 닫기
export const MENU_CLOSE = "MENU_CLOSE";
export const MENU_CLOSE_REQUEST = "MENU_CLOSE_REQUEST";

// main 페이지 데이터 요청
export const MAIN_DATA = "MAIN_DATA";
export const MAIN_DATA_REQUEST = "MAIN_DATA_REQUEST";
export const MAIN_DATA_SUCCESS = "MAIN_DATA_SUCCESS";
export const MAIN_DATA_FAILURE = "MAIN_DATA_FAILURE";

// trend 페이지 데이터 요청
export const TREND_DATA = "TREND_DATA";
export const TREND_DATA_REQUEST = "TREND_DATA_REQUEST";
export const TREND_DATA_SUCCESS = "TREND_DATA_SUCCESS";
export const TREND_DATA_FAILURE = "TREND_DATA_FAILURE";

// header에 데이터 전달
export const HEADER_DATA_TRANSMIT = "HEADER_DATA_TRANSMISSION";
export const HEADER_DATA_TRANSMIT_REQUEST = "HEADER_DATA_TRANSMISSION_REQUEST";
export const HEADER_DATA_TRANSMIT_SUCCESS = "HEADER_DATA_TRANSMIT_SUCCESS";
export const HEADER_DATA_TRANSMIT_FAILURE = "HEADER_DATA_TRANSMIT_FAILURE";

// 장소 변경에 대한 데이터 변경 요청
export const CHANGE_PLACE = "CHANGE_PLACE";
export const CHANGE_PLACE_REQUEST = "CHANGE_PLACE_REQUEST";
export const CHANGE_PLACE_SUCCESS = "CHANGE_PLACE_SUCCESS";
export const CHANGE_PLACE_FAILURE = "CHANGE_PLACE_FAILURE";

// street shot 요청
export const STREETSHOT = "STREETSHOT";
export const STREETSHOT_REQUEST = "STREETSHOT_REQUEST";
export const STREETSHOT_SUCCESS = "STREETSHOT_SUCCESS";
export const STREETSHOT_FAILURE = "STREETSHOT_FAILURE";

//장치 상태 요청
export const DEVICE_STATUS = "DEVICE_STATUS";
export const DEVICE_STATUS_REQUEST = "DEVICE_STATUS_REQUEST";
export const DEVICE_STATUS_SUCCESS = "DEVICE_STATUS_SUCCESS";
export const DEVICE_STATUS_FAILURE = "DEVICE_STATUS_FAILURE";
//장치 on
export const DEVICE_ON = "DEVICE_ON";
export const DEVICE_ON_REQUEST = "DEVICE_ON_REQUEST";
export const DEVICE_ON_SUCCESS = "DEVICE_ON_SUCCESS";
export const DEVICE_ON_FAILURE = "DEVICE_ON_FAILURE";
//장치 OFF
export const DEVICE_OFF = "DEVICE_OFF";
export const DEVICE_OFF_REQUEST = "DEVICE_OFF_REQUEST";
export const DEVICE_OFF_SUCCESS = "DEVICE_OFF_SUCCESS";
export const DEVICE_OFF_FAILURE = "DEVICE_OFF_FAILURE";
